[package]
name = "copyless"
description = "Ways to eliminate memcpy calls when using the standard library."
version = "0.1.0"
authors = ["Dzmitry Malyshau <kvarkus@gmail.com>"]
edition = "2018"

[dependencies]
